configuration: release

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - BugFixes

# Restore nuget packages before running msbuild
image: 
  - Visual Studio 2017
before_build:
  - nuget restore LBP/LBP.sln
  
# package Web application project for Web deploy
build:
  verbosity: minimal
  publish_wap: true

test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"LBP\LBP.UnitTests\obj\Debug\LBP.UnitTests.dll -noshadow" -output:"coverage.xml" -filter:"+[YourSUTNamepace*]* -[YourTestNamespace*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t YourUploadToken
